name: papa_meteo
description: (unofficial) ICM meteo.pl weather forecasts in Android app with home screen widget.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  tuple: ^2.0.1
  provider: ^6.0.5
  intl: ^0.18.0
  home_widget: ^0.2.0+1
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
